# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import weather_pb2 as proto_dot_weather__pb2


class WeatherServiceStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/weather.WeatherService/subscribe',
                request_serializer=proto_dot_weather__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=proto_dot_weather__pb2.Forecast.FromString,
                )


class WeatherServiceServicer(object):
    """Missing associated documentation comment in .proto file"""

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=proto_dot_weather__pb2.SubscribeRequest.FromString,
                    response_serializer=proto_dot_weather__pb2.Forecast.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'weather.WeatherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WeatherService(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/weather.WeatherService/subscribe',
            proto_dot_weather__pb2.SubscribeRequest.SerializeToString,
            proto_dot_weather__pb2.Forecast.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
