# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/weather.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/weather.proto',
  package='weather',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13proto/weather.proto\x12\x07weather\"<\n\x04Wind\x12\r\n\x05speed\x18\x01 \x01(\x05\x12%\n\tdirection\x18\x02 \x01(\x0e\x32\x12.weather.Direction\"s\n\x07Weather\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x11\n\thumindity\x18\x02 \x01(\x05\x12#\n\x08\x63loudity\x18\x03 \x01(\x0e\x32\x11.weather.Cloudity\x12\x1b\n\x04wind\x18\x04 \x01(\x0b\x32\r.weather.Wind\"M\n\x08\x46orecast\x12\x10\n\x08\x64\x61tetime\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12!\n\x07weather\x18\x03 \x03(\x0b\x32\x10.weather.Weather\" \n\x10SubscribeRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t*5\n\tDirection\x12\t\n\x05NORTH\x10\x00\x12\t\n\x05SOUTH\x10\x01\x12\x08\n\x04\x45\x41ST\x10\x02\x12\x08\n\x04WEST\x10\x03*8\n\x08\x43loudity\x12\t\n\x05SUNNY\x10\x00\x12\n\n\x06\x43LOUDY\x10\x01\x12\t\n\x05RAINY\x10\x02\x12\n\n\x06STORMY\x10\x03\x32O\n\x0eWeatherService\x12=\n\tsubscribe\x12\x19.weather.SubscribeRequest\x1a\x11.weather.Forecast\"\x00\x30\x01\x62\x06proto3'
)

_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='weather.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NORTH', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOUTH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EAST', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEST', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=324,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_DIRECTION)

Direction = enum_type_wrapper.EnumTypeWrapper(_DIRECTION)
_CLOUDITY = _descriptor.EnumDescriptor(
  name='Cloudity',
  full_name='weather.Cloudity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUNNY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUDY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAINY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STORMY', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=379,
  serialized_end=435,
)
_sym_db.RegisterEnumDescriptor(_CLOUDITY)

Cloudity = enum_type_wrapper.EnumTypeWrapper(_CLOUDITY)
NORTH = 0
SOUTH = 1
EAST = 2
WEST = 3
SUNNY = 0
CLOUDY = 1
RAINY = 2
STORMY = 3



_WIND = _descriptor.Descriptor(
  name='Wind',
  full_name='weather.Wind',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='weather.Wind.speed', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='weather.Wind.direction', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=92,
)


_WEATHER = _descriptor.Descriptor(
  name='Weather',
  full_name='weather.Weather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='weather.Weather.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humindity', full_name='weather.Weather.humindity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cloudity', full_name='weather.Weather.cloudity', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wind', full_name='weather.Weather.wind', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=209,
)


_FORECAST = _descriptor.Descriptor(
  name='Forecast',
  full_name='weather.Forecast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datetime', full_name='weather.Forecast.datetime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='weather.Forecast.city', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weather', full_name='weather.Forecast.weather', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=288,
)


_SUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='weather.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='weather.SubscribeRequest.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=322,
)

_WIND.fields_by_name['direction'].enum_type = _DIRECTION
_WEATHER.fields_by_name['cloudity'].enum_type = _CLOUDITY
_WEATHER.fields_by_name['wind'].message_type = _WIND
_FORECAST.fields_by_name['weather'].message_type = _WEATHER
DESCRIPTOR.message_types_by_name['Wind'] = _WIND
DESCRIPTOR.message_types_by_name['Weather'] = _WEATHER
DESCRIPTOR.message_types_by_name['Forecast'] = _FORECAST
DESCRIPTOR.message_types_by_name['SubscribeRequest'] = _SUBSCRIBEREQUEST
DESCRIPTOR.enum_types_by_name['Direction'] = _DIRECTION
DESCRIPTOR.enum_types_by_name['Cloudity'] = _CLOUDITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Wind = _reflection.GeneratedProtocolMessageType('Wind', (_message.Message,), {
  'DESCRIPTOR' : _WIND,
  '__module__' : 'proto.weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.Wind)
  })
_sym_db.RegisterMessage(Wind)

Weather = _reflection.GeneratedProtocolMessageType('Weather', (_message.Message,), {
  'DESCRIPTOR' : _WEATHER,
  '__module__' : 'proto.weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.Weather)
  })
_sym_db.RegisterMessage(Weather)

Forecast = _reflection.GeneratedProtocolMessageType('Forecast', (_message.Message,), {
  'DESCRIPTOR' : _FORECAST,
  '__module__' : 'proto.weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.Forecast)
  })
_sym_db.RegisterMessage(Forecast)

SubscribeRequest = _reflection.GeneratedProtocolMessageType('SubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBEREQUEST,
  '__module__' : 'proto.weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.SubscribeRequest)
  })
_sym_db.RegisterMessage(SubscribeRequest)



_WEATHERSERVICE = _descriptor.ServiceDescriptor(
  name='WeatherService',
  full_name='weather.WeatherService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=437,
  serialized_end=516,
  methods=[
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='weather.WeatherService.subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=_FORECAST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHERSERVICE)

DESCRIPTOR.services_by_name['WeatherService'] = _WEATHERSERVICE

# @@protoc_insertion_point(module_scope)
